Repository RicardoTaverna/medonvet, pull requests merged in 2022-09, with the labels that each got.

#28 [MOV-031] - adicionado funcoes de crud para agendamentos.
  backend/src/agendamento/__init__.py
  backend/src/agendamento/admin.py
  backend/src/agendamento/apps.py
  backend/src/agendamento/migrations/0001_initial.py
  backend/src/agendamento/migrations/__init__.py
  backend/src/agendamento/models.py
  backend/src/agendamento/serializers.py
  backend/src/agendamento/tests.py
  backend/src/agendamento/urls.py
  backend/src/agendamento/views.py
  backend/src/aplicacoes/views.py
  backend/src/medonvet/settings.py
  backend/src/medonvet/urls.py
Labels: enhancement

#29 [MOV-029] Criado a tela de aplicações/dose
  backend/src/aplicacoes/migrations/0002_aplicacao_data_reaplicacao_aplicacao_notificar.py
  backend/src/aplicacoes/models.py
  backend/src/aplicacoes/serializers.py
  frontend/medonvet/package-lock.json
  frontend/medonvet/src/components/AplicacaoPetInfo/index.js
  frontend/medonvet/src/components/AplicacaoVeterinario/index.js
  frontend/medonvet/src/components/AplicacaoVeterinario/servico.css
  frontend/medonvet/src/pages/VeterinarioPage/index.js
Labels: enhancement

#30 Mov 032
  backend/src/agendamento/migrations/0002_rename_domingo_horariofuncionamento_dia_0_and_more.py
  backend/src/agendamento/migrations/0003_alter_horariofuncionamento_inicio_and_more.py
  backend/src/agendamento/migrations/0004_agendamento_servico.py
  backend/src/agendamento/migrations/0005_remove_agendamento_funcionamento_and_more.py
  backend/src/agendamento/migrations/0006_agendamento_pet_alter_agendamento_veterinario.py
  backend/src/agendamento/migrations/0007_alter_agendamento_horario_selecionado.py
  backend/src/agendamento/models.py
  backend/src/agendamento/serializers.py
  backend/src/agendamento/urls.py
  backend/src/agendamento/views.py
  frontend/medonvet/src/components/ClienteServicos/index.js
  frontend/medonvet/src/components/HorarioCard/index.js
  frontend/medonvet/src/components/PrestadorAgenda/PrestadorAgenda.css
  frontend/medonvet/src/components/PrestadorAgenda/index.js
  frontend/medonvet/src/components/PrestadorConfig/index.js
  frontend/medonvet/src/components/PrestadorConfigHorario/index.js
  frontend/medonvet/src/components/ServicoCard/index.js
  frontend/medonvet/src/components/VeterinarioAgendaCard/AgendamentoCard.css
  frontend/medonvet/src/components/VeterinarioAgendaCard/index.js
  frontend/medonvet/src/components/VeterinarioAgendaDay/index.js
  frontend/medonvet/src/components/VeterinarioAgendaDayCard/VeterinarioAgendaDayCard.css
  frontend/medonvet/src/components/VeterinarioAgendaDayCard/index.js
  frontend/medonvet/src/components/VeterinarioConfig/index.js
  frontend/medonvet/src/components/VeterinarioHome/index.js
  frontend/medonvet/src/pages/ClienteAgendamento/index.js
  frontend/medonvet/src/pages/VeterinarioPage/index.js
  frontend/medonvet/src/services/api.js
  frontend/medonvet/src/services/routes.js
Labels: bug, enhancement, help wanted, invalid, question

#31 Mov 034
  backend/src/servicos/urls.py
  backend/src/servicos/views.py
  frontend/medonvet/package-lock.json
  frontend/medonvet/src/components/ClientePrestadores/index.js
  frontend/medonvet/src/components/ClienteServicos/index.js
  frontend/medonvet/src/components/PrestadorAgenda/index.js
  frontend/medonvet/src/components/ServicosVeterinario/index.js
Labels: enhancement

#32 [MOV-033] Criado login para veterinario.
  backend/src/prestadores/views.py
  backend/src/usuarios/serializers.py
  backend/src/usuarios/urls.py
  backend/src/usuarios/views.py
  frontend/medonvet/src/components/CadastroCliente/index.js
  frontend/medonvet/src/components/CadastroPrestador/index.js
  frontend/medonvet/src/components/CadastroVeterinario/index.js
  frontend/medonvet/src/components/PrestadorHome/index.js
  frontend/medonvet/src/components/Veterinario/index.js
  frontend/medonvet/src/components/VeterinarioHome/index.js
Labels: enhancement

#33 [MOV-035] - conectado microservico de imagens
  backend/src/clientes/migrations/0008_alter_pet_imagem.py
  backend/src/clientes/models.py
  backend/src/prestadores/migrations/0011_alter_prestador_avatar_alter_prestador_capa_and_more.py
  backend/src/prestadores/models.py
  frontend/medonvet/src/components/ClientePrestadores/index.js
  frontend/medonvet/src/components/Pets/index.js
  frontend/medonvet/src/components/PrestadorCard/index.js
  frontend/medonvet/src/components/ServicoCard/index.js
  frontend/medonvet/src/components/VeterinarioConfigCadastro/index.js
  frontend/medonvet/src/pages/VeterinarioPage/index.js
  frontend/medonvet/src/services/api.js
Labels: enhancement

#34 [MOV-035] - Microservico para disparo de emails.
  backend/.gitignore
  backend/docker-compose.yml
  backend/requirements.txt
  backend/services/mailservice/__init__.py
  backend/services/mailservice/main.py
  backend/services/mailservice/templates/__init__.py
  backend/services/mailservice/templates/agendamento.html
  backend/services/mailservice/templates/img/MedOnVet.png
  backend/services/mailservice/templates/img/logo2.png
  backend/services/mailservice/templates/img/programmer.png
  backend/services/mailservice/templates/img/soc_1.png
  backend/services/mailservice/templates/img/soc_2.png
  backend/services/mailservice/templates/img/soc_3.png
  backend/services/mailservice/templates/img/soc_4.png
  backend/services/mailservice/templates/reset_password.html
  backend/services/mailservice/templates/templates.py
  backend/src/emailer/serializers.py
  backend/src/emailer/urls.py
  backend/src/emailer/views.py
  frontend/medonvet/src/components/HorarioCard/index.js
Labels: enhancement, help wanted
