Repository RicardoTaverna/medonvet, pull requests merged in 2022-08, with the labels that each got.

#18 Mov 021
  backend/requirements.txt
  backend/src/medonvet/settings.py
  backend/src/prestadores/migrations/0007_prestador_status.py
  backend/src/prestadores/migrations/0008_alter_prestador_status.py
  backend/src/prestadores/migrations/0009_remove_prestador_status_alter_prestador_avatar_and_more.py
  backend/src/prestadores/models.py
  backend/src/usuarios/serializers.py
  backend/src/usuarios/views.py
  frontend/medonvet/src/components/PrestadorConfig/index.js
  frontend/medonvet/src/components/PrestadorConfigCadastro/index.js
  frontend/medonvet/src/components/PrestadorConfigSeguranca/index.js
Labels: enhancement, help wanted, question

#20 Mov 022
  backend/src/prestadores/admin.py
  backend/src/prestadores/migrations/0010_remove_veterinario_prestador_and_more.py
  backend/src/prestadores/models.py
  backend/src/prestadores/serializers.py
  backend/src/prestadores/urls.py
  backend/src/prestadores/views.py
  frontend/medonvet/package-lock.json
  frontend/medonvet/src/components/PrestadorHome/index.js
  frontend/medonvet/src/components/Veterinario/index.js
Labels: bug, enhancement, help wanted

#22 [MOV-024] - criado rotas e controllers para o servico de aplicação, a…
  backend/src/aplicacoes/__init__.py
  backend/src/aplicacoes/admin.py
  backend/src/aplicacoes/apps.py
  backend/src/aplicacoes/migrations/0001_initial.py
  backend/src/aplicacoes/migrations/__init__.py
  backend/src/aplicacoes/models.py
  backend/src/aplicacoes/serializers.py
  backend/src/aplicacoes/tests.py
  backend/src/aplicacoes/urls.py
  backend/src/aplicacoes/views.py
  backend/src/medonvet/settings.py
  backend/src/medonvet/urls.py
  frontend/medonvet/src/components/AplicacaoPetInfo/index.js
  frontend/medonvet/src/components/Pets/index.js
Labels: enhancement, question

#23 [MOV-025] - Criado rotas, controller , views de serviços.
  backend/src/medonvet/settings.py
  backend/src/medonvet/urls.py
  backend/src/servicos/__init__.py
  backend/src/servicos/admin.py
  backend/src/servicos/apps.py
  backend/src/servicos/migrations/0001_initial.py
  backend/src/servicos/migrations/__init__.py
  backend/src/servicos/models.py
  backend/src/servicos/serializers.py
  backend/src/servicos/tests.py
  backend/src/servicos/urls.py
  backend/src/servicos/views.py
Labels: enhancement

#24 [MOV-026] Criado DashBoard Serviços
  backend/src/servicos/migrations/0002_servico_veterinario_alter_servico_prestador.py
  backend/src/servicos/models.py
  backend/src/servicos/serializers.py
  backend/src/servicos/views.py
  frontend/medonvet/src/components/ServicosVeterinario/index.js
  frontend/medonvet/src/components/ServicosVeterinario/servico.css
  frontend/medonvet/src/pages/PrestadorPage/index.js
  frontend/medonvet/src/pages/VeterinarioPage/index.js
Labels: enhancement

#25 Mov 027
  .vscode/settings.json
  backend/src/medonvet/fixtures/initial_fixture.json
  backend/src/medonvet/settings.py
  backend/src/prestadores/urls.py
  backend/src/prestadores/views.py
  backend/src/servicos/urls.py
  backend/src/servicos/views.py
  frontend/medonvet/package-lock.json
  frontend/medonvet/src/assets/images/aplicacao-sm.png
  frontend/medonvet/src/assets/images/aplicacao.png
  frontend/medonvet/src/assets/images/cirurgia-sm.png
  frontend/medonvet/src/assets/images/cirurgia.png
  frontend/medonvet/src/assets/images/medicine-sm.png
  frontend/medonvet/src/assets/images/medicine.png
  frontend/medonvet/src/assets/images/veterinary-sm.png
  frontend/medonvet/src/assets/images/veterinary.png
  frontend/medonvet/src/components/ClientePrestadores/index.js
  frontend/medonvet/src/components/ClientePrestadoresMapa/index.js
  frontend/medonvet/src/components/ClienteServicos/ClientServicos.css
  frontend/medonvet/src/components/ClienteServicos/index.js
  frontend/medonvet/src/components/PrestadorCard/index.js
  frontend/medonvet/src/components/ServicoCard/ServicoCard.css
  frontend/medonvet/src/components/ServicoCard/index.js
  frontend/medonvet/src/pages/ClientApp/index.js
  frontend/medonvet/src/services/googleMaps.js
Labels: enhancement

#27 [MOV-030] - adicionada nova api para gerenciar as imagens.
  .gitignore
  .vscode/launch.json
  backend/.gitignore
  backend/Dockerfile
  backend/docker-compose.yml
  backend/requirements.txt
  backend/services/__init__.py
  backend/services/imgservice/__init__.py
  backend/services/imgservice/database/__init__.py
  backend/services/imgservice/database/dao.py
  backend/services/imgservice/main.py
  backend/services/imgservice/models/__init__.py
  backend/services/imgservice/models/images.py
  backend/services/imgservice/routes/__init__.py
  backend/services/imgservice/routes/images.py
  backend/services/imgservice/settings.py
Labels: enhancement
