Repository RicardoTaverna/medonvet, pull requests merged in 2022-04, with the labels that each got.

#3 Mov 003
  backend/src/medonvet/settings.py
  backend/src/usuarios/tests.py
  backend/src/usuarios/urls.py
  backend/src/usuarios/views.py
Labels: enhancement, question

#4 Mov 004
  backend/src/clientes/admin.py
  backend/src/clientes/migrations/0002_pet.py
  backend/src/clientes/migrations/0003_alter_pet_idcliente.py
  backend/src/clientes/migrations/0004_rename_idcliente_pet_cliente.py
  backend/src/clientes/models.py
  backend/src/clientes/serializers.py
  backend/src/clientes/tests.py
  backend/src/clientes/urls.py
  backend/src/clientes/views.py
Labels: enhancement

#5 Mov 007
  backend/requirements.txt
  backend/src/clientes/serializers.py
  backend/src/clientes/urls.py
  backend/src/clientes/views.py
  backend/src/medonvet/settings.py
  backend/src/usuarios/urls.py
  backend/src/usuarios/views.py
  frontend/medonvet/package-lock.json
  frontend/medonvet/package.json
  frontend/medonvet/src/App.js
  frontend/medonvet/src/assets/images/MedOnVet.png
  frontend/medonvet/src/assets/images/app_background.jpg
  frontend/medonvet/src/assets/images/dog_cat_cute.png
  frontend/medonvet/src/assets/images/login_background.png
  frontend/medonvet/src/assets/images/logo2.png
  frontend/medonvet/src/assets/images/medonvet_claro.png
  frontend/medonvet/src/assets/images/medonvet_escuro.png
  frontend/medonvet/src/components/ClientApp/ClientApp.css
  frontend/medonvet/src/components/ClientApp/index.js
  frontend/medonvet/src/components/ClientApp/perfil_background.jpg
  frontend/medonvet/src/components/Footer/index.js
  frontend/medonvet/src/components/Navbar/index.js
  frontend/medonvet/src/components/NavbarApp/index.js
  frontend/medonvet/src/index.js
  frontend/medonvet/src/pages/App/index.js
  frontend/medonvet/src/pages/AppPage/index.js
  frontend/medonvet/src/pages/HomePage/index.js
  frontend/medonvet/src/pages/Login/index.js
  frontend/medonvet/src/services/api.js
  frontend/medonvet/src/services/auth.js
  frontend/medonvet/src/services/routes.js
  images/MedOnVet-claro.png
  images/MedOnVet-escuro.png
  images/MedOnVet.png
  images/image_processing20200424-17190-o5tny5.png
  images/medonvet_claro.png
  images/medonvet_escuro.png
Labels: enhancement

#6 Mov 006
  README.md
  backend/src/medonvet/settings.py
  backend/src/medonvet/urls.py
  backend/src/prestadores/__init__.py
  backend/src/prestadores/admin.py
  backend/src/prestadores/apps.py
  backend/src/prestadores/migrations/0001_initial.py
  backend/src/prestadores/migrations/0002_alter_prestador_user.py
  backend/src/prestadores/migrations/0003_alter_prestador_user.py
  backend/src/prestadores/migrations/__init__.py
  backend/src/prestadores/models.py
  backend/src/prestadores/serializers.py
  backend/src/prestadores/urls.py
  backend/src/prestadores/views.py
  backend/src/usuarios/tests.py
  backend/src/usuarios/urls.py
  backend/src/usuarios/views.py
Labels: enhancement

#7 Mov 005 - backend para troca de senha
  .github/pull_request_template.md
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  backend/docker-compose.yml
  backend/requirements.txt
  backend/src/emailer/__init__.py
  backend/src/emailer/admin.py
  backend/src/emailer/apps.py
  backend/src/emailer/migrations/__init__.py
  backend/src/emailer/models.py
  backend/src/emailer/serializers.py
  backend/src/emailer/templates/img/MedOnVet.png
  backend/src/emailer/templates/img/logo2.png
  backend/src/emailer/templates/img/programmer.png
  backend/src/emailer/templates/img/soc_1.png
  backend/src/emailer/templates/img/soc_2.png
  backend/src/emailer/templates/img/soc_3.png
  backend/src/emailer/templates/img/soc_4.png
  backend/src/emailer/templates/reset_password.html
  backend/src/emailer/tests.py
  backend/src/emailer/urls.py
  backend/src/emailer/views.py
  backend/src/medonvet/settings.py
  backend/src/medonvet/urls.py
  backend/src/usuarios/admin.py
  backend/src/usuarios/migrations/0004_resetpassword.py
  backend/src/usuarios/migrations/0005_alter_resetpassword_token.py
  backend/src/usuarios/migrations/0006_alter_resetpassword_data_solicitacao.py
  backend/src/usuarios/migrations/0007_alter_resetpassword_data_solicitacao.py
  backend/src/usuarios/migrations/0008_alter_resetpassword_data_solicitacao.py
  backend/src/usuarios/models.py
  backend/src/usuarios/serializers.py
  backend/src/usuarios/tests.py
  backend/src/usuarios/urls.py
  backend/src/usuarios/views.py
Labels: enhancement

#8 Mov 008
  backend/src/usuarios/serializers.py
  backend/src/usuarios/views.py
  frontend/medonvet/package-lock.json
  frontend/medonvet/package.json
  frontend/medonvet/src/assets/images/cadastro_background.png
  frontend/medonvet/src/components/CadastroPrestador/index.js
  frontend/medonvet/src/pages/Cadastro/index.js
  frontend/medonvet/src/pages/Login/index.js
  frontend/medonvet/src/services/api.js
  frontend/medonvet/src/services/routes.js
Labels: enhancement

#9 Mov 009
  backend/requirements.txt
  backend/src/clientes/migrations/0005_pet_data_nascimento.py
  backend/src/clientes/migrations/0006_pet_imagem.py
  backend/src/clientes/models.py
  backend/src/clientes/urls.py
  backend/src/media/pets/bernese-p.jpg
  backend/src/medonvet/settings.py
  backend/src/medonvet/urls.py
  frontend/medonvet/package-lock.json
  frontend/medonvet/src/components/Pets/index.js
  frontend/medonvet/src/components/Pets/pets.css
  frontend/medonvet/src/pages/App/app.css
  frontend/medonvet/src/pages/App/index.js
  frontend/medonvet/src/pages/AppPage/index.js
  frontend/medonvet/src/pages/ClientApp/ClientApp.css
  frontend/medonvet/src/pages/ClientApp/index.js
  frontend/medonvet/src/pages/ClientApp/perfil_background.jpg
Labels: enhancement

#11 [MOV-011] - paginas para troca de senha.
  backend/src/emailer/templates/reset_password.html
  backend/src/medonvet/settings.py
  backend/src/usuarios/views.py
  frontend/medonvet/src/assets/images/recuperar-senha.png
  frontend/medonvet/src/components/Pets/index.js
  frontend/medonvet/src/pages/Login/index.js
  frontend/medonvet/src/pages/RecuperarSenha/index.js
  frontend/medonvet/src/services/routes.js
Labels: bug, enhancement
